name: Firebase Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: get list
        run: ls -al

      - name: Initialize
        run: npm install

      - name: Run Deploy
        run: npm run deploy
