name: Firebase Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize
        run: rm -rf ./package-lock.json && npm install

      - name: Run Deploy
        run: npm run deploy
