name: Firebase Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: get list
        run: ls -al

      - name: Initialize
        run: npm install

      - name: Run Deploy
        run: npm run deploy
